name: Python Ruff

on: [push, pull_request]

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout
        uses: actions/checkout@master

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Lint with ruff
        run: uvx ruff check src tests
